project_id = "tqfbrgoaucjcttfsimdh"

[functions.generate-sitemap]
verify_jwt = false

[functions.track-conversion]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.fetch-youtube-videos]
verify_jwt = false

[functions.get-website-leads]
verify_jwt = false

[functions.get-bookings]
verify_jwt = false

[functions.send-booking-webhook]
verify_jwt = false

[functions.google-hotel-feeds]
verify_jwt = false
